name: seventh_devtest
version: 1.0.0+1
publish_to: none
description: Projecto de tests.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  flutter_svg: ^2.0.2
  validatorless: ^1.2.3
  chewie: 
  video_player: 
 
dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets\seventh_logo.svg
    

